# Модуль 11. Работа с HTML-страницами и API ВКонтакте

# Блок 2. Библиотека requests и курсы валют > Шаг 1. Постановка задачи Previous Subsection

### ПОСТАНОВКА ЗАДАЧИ. УЧИМСЯ ВЫГРУЖАТЬ КУРСЫ ВАЛЮТ С САЙТА

Курс валют – полезная и регулярно обновляемая информация. Залезать каждый раз на сайт за курсом глупо. Значит, вам нужен скрипт, который будет в удобном виде выгружать информацию по курсам валют.

В этом блоке мы рассмотрим основы веб-запросов и работы с API на примере задачи получения курсов валют. Будем использовать сервис cbr-xml-daily.ru. Итак, нам необходима функция, возвращающая курс заданной валюты в двух форматах:

1. Только значение курса валюты.

2. Полную информацию о валюте: курс, название, номинал и другие характеристики.

# Шаг 2. Веб-запросы

Сначала разберемся, как получить информацию с внешнего сервиса. Для этого есть много библиотек, самой распространенной является requests. Импортируем ее и отправим запрос к сервису:

In [1]:
import pandas as pd

In [2]:
import requests

In [2]:
r = requests.get('https://www.cbr-xml-daily.ru/daily_json.js')

In [3]:
print(r)

<Response [200]>


Мы получили объект ответа, который содержит всю нужную нам информацию. По умолчанию на экран выводится HTTP-код ответа 200. Это означает, что запрос был корректным, и сервер отдал нам нужную информацию. Более подробную информацию о кодах состояния HTTP можно прочитать по ссылке (https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP).

Код ответа в виде числа можно получить с помощью метода status_code:

In [4]:
print(r.status_code)

200


# Шаг. 3 Содержимое ответа

Нужная нам информация содержится в тексте ответа сервера. Можно получить ее с помощью метода text:

In [5]:
print(r.text)

{
    "Date": "2019-04-04T11:30:00+03:00",
    "PreviousDate": "2019-04-03T11:30:00+03:00",
    "PreviousURL": "\/\/www.cbr-xml-daily.ru\/archive\/2019\/04\/03\/daily_json.js",
    "Timestamp": "2019-04-03T15:00:00+03:00",
    "Valute": {
        "AUD": {
            "ID": "R01010",
            "NumCode": "036",
            "CharCode": "AUD",
            "Nominal": 1,
            "Name": "Австралийский доллар",
            "Value": 46.3771,
            "Previous": 46.3284
        },
        "AZN": {
            "ID": "R01020A",
            "NumCode": "944",
            "CharCode": "AZN",
            "Nominal": 1,
            "Name": "Азербайджанский манат",
            "Value": 38.4108,
            "Previous": 38.5927
        },
        "GBP": {
            "ID": "R01035",
            "NumCode": "826",
            "CharCode": "GBP",
            "Nominal": 1,
            "Name": "Фунт стерлингов Соединенного королевства",
            "Value": 85.7687,
            "Previous": 85.5269
   

Однако работать с ответом сервера в виде строки крайне неудобно. Гораздо проще вызвать метод json(), который сразу преобразует строку в словарь:

In [6]:
data = r.json()
data

{'Date': '2019-04-04T11:30:00+03:00',
 'PreviousDate': '2019-04-03T11:30:00+03:00',
 'PreviousURL': '//www.cbr-xml-daily.ru/archive/2019/04/03/daily_json.js',
 'Timestamp': '2019-04-03T15:00:00+03:00',
 'Valute': {'AUD': {'ID': 'R01010',
   'NumCode': '036',
   'CharCode': 'AUD',
   'Nominal': 1,
   'Name': 'Австралийский доллар',
   'Value': 46.3771,
   'Previous': 46.3284},
  'AZN': {'ID': 'R01020A',
   'NumCode': '944',
   'CharCode': 'AZN',
   'Nominal': 1,
   'Name': 'Азербайджанский манат',
   'Value': 38.4108,
   'Previous': 38.5927},
  'GBP': {'ID': 'R01035',
   'NumCode': '826',
   'CharCode': 'GBP',
   'Nominal': 1,
   'Name': 'Фунт стерлингов Соединенного королевства',
   'Value': 85.7687,
   'Previous': 85.5269},
  'AMD': {'ID': 'R01060',
   'NumCode': '051',
   'CharCode': 'AMD',
   'Nominal': 100,
   'Name': 'Армянских драмов',
   'Value': 13.3724,
   'Previous': 13.4441},
  'BYN': {'ID': 'R01090B',
   'NumCode': '933',
   'CharCode': 'BYN',
   'Nominal': 1,
   'Name': 'Б

# Шаг 4. Извлекаем нужные данные

Теперь очень просто извлечь данные о курсах валют из ответа сервера. Для этого достаточно обратиться к ключу словаря 'Valute':

In [7]:
data['Valute']

{'AUD': {'ID': 'R01010',
  'NumCode': '036',
  'CharCode': 'AUD',
  'Nominal': 1,
  'Name': 'Австралийский доллар',
  'Value': 46.3771,
  'Previous': 46.3284},
 'AZN': {'ID': 'R01020A',
  'NumCode': '944',
  'CharCode': 'AZN',
  'Nominal': 1,
  'Name': 'Азербайджанский манат',
  'Value': 38.4108,
  'Previous': 38.5927},
 'GBP': {'ID': 'R01035',
  'NumCode': '826',
  'CharCode': 'GBP',
  'Nominal': 1,
  'Name': 'Фунт стерлингов Соединенного королевства',
  'Value': 85.7687,
  'Previous': 85.5269},
 'AMD': {'ID': 'R01060',
  'NumCode': '051',
  'CharCode': 'AMD',
  'Nominal': 100,
  'Name': 'Армянских драмов',
  'Value': 13.3724,
  'Previous': 13.4441},
 'BYN': {'ID': 'R01090B',
  'NumCode': '933',
  'CharCode': 'BYN',
  'Nominal': 1,
  'Name': 'Белорусский рубль',
  'Value': 30.4263,
  'Previous': 30.5647},
 'BGN': {'ID': 'R01100',
  'NumCode': '975',
  'CharCode': 'BGN',
  'Nominal': 1,
  'Name': 'Болгарский лев',
  'Value': 37.4247,
  'Previous': 37.5008},
 'BRL': {'ID': 'R01115',
  '

### Упражнение

Обратитесь к ключу 'INR' словаря data['Valute'] и затем получите из этого результата код валюты (ключ 'ID'). Какой код у валюты INR?

In [9]:
data['Valute']['INR']['ID']

'R01270'

# Шаг 5. Оформляем функцию


Давайте оформим наши вычисления в отдельную функцию, которой будет удобно пользоваться. На вход она должна принимать два параметра:

1. Название валюты currency. Например, 'EUR' или 'USD'.

2. Формат ответа format. При значении 'full' будем отдавать все, что знаем о валюте. Например, для currency = 'USD':

In [10]:
{'CharCode': 'USD',
   'ID': 'R01235',
   'Name': 'Доллар США',
   'Nominal': 1,
   'NumCode': '840',
   'Previous': 68.2505,
   'Value': 69.0286}

{'CharCode': 'USD',
 'ID': 'R01235',
 'Name': 'Доллар США',
 'Nominal': 1,
 'NumCode': '840',
 'Previous': 68.2505,
 'Value': 69.0286}

А при значении format = 'value' только значение ключа 'Value', т. е. курс: 69.0286.

Оформим наши требования в коде:

In [11]:
def exchange_rates(currency, format='full'):
    response = requests.get('https://www.cbr-xml-daily.ru/daily_json.js').json()['Valute']
    data = response[currency] 
    if format == 'full':
        return data  
    elif format == 'value':
        return data['Value']

# Шаг 6. Некорректная валюта

Перед тем, как протестировать нашу функцию, добавим еще одну проверку: если пользователь ввел несуществующую валюту, то надо вернуть предупреждение. Аналогичную проверку добавим и для формата:

In [12]:
def exchange_rates(currency, format='full'):
    response = requests.get('https://www.cbr-xml-daily.ru/daily_json.js').json()['Valute']  
    if currency in response:
        data = response[currency]   
    else:
        return 'Unknown currency!'  
    if format == 'full':
        return data   
    elif format == 'value':
        return data['Value']
    else:
        return 'Unknown format!'

Теперь проверим корректность работы:

1. Валюта корректна, формат  'full':

In [13]:
exchange_rates(currency='USD')

{'ID': 'R01235',
 'NumCode': '840',
 'CharCode': 'USD',
 'Nominal': 1,
 'Name': 'Доллар США',
 'Value': 65.1639,
 'Previous': 65.4726}

In [14]:
exchange_rates('EUR', 'value')

73.1725

In [15]:
exchange_rates('EUR/USD')

'Unknown currency!'

In [16]:
exchange_rates('EUR', '12345')

'Unknown format!'

In [30]:
exchange_rates('PLN')

{'ID': 'R01565',
 'NumCode': '985',
 'CharCode': 'PLN',
 'Nominal': 1,
 'Name': 'Польский злотый',
 'Value': 17.0591,
 'Previous': 17.0542}

Теперь наша функция полностью готова к использованию в отчетах.

# Шаг 8. Проверочное задание

Напишите функцию, которая по ID валюты возвращает ее название на русском языке. Например, для кода 'R01700J' это 'Турецкая лира'.

Какое значение должна вернуть функция для ID валюты 'R01565'?

In [21]:
def currency_name(idenf):
    response = requests.get('https://www.cbr-xml-daily.ru/daily_json.js').json()['Valute'] 
    print (response)
    for currency in response:
    if idenf in response:
        data = response[Name] 
        return data['Value']
    else:
        return 'Unknown ID!'

In [50]:
def currency_name(idenf):
    response = requests.get('https://www.cbr-xml-daily.ru/daily_json.js').json()['Valute'] 
    # print (response)
    for k, v in response.items():
        #print (k)
        #print (v['ID'])
        if idenf == v['ID']:
        #data = response[k]
        #print (data)
            return v['Name']

In [51]:
currency_name('R01565')

'Польский злотый'

# Блок 3. Удобный парсинг HTML-страниц > Шаг 1. Постановка задачи

Довольно часто приходится добывать информацию не с помощью удобных API, а прямо с HTML-страниц. Получить содержимое страницы в большинстве случаев несложно, труднее извлечь из HTML-кода нужную информацию. В качестве примера мы рассмотрим страницу новости на Lenta.ru, из которой будем доставать полезную информацию:

1. Заголовок страницы.

2. Редакторский заголовок перед текстом.

3. Дату публикации.

4. Текст публикации.

5. Все ссылки на странице.

# Шаг 2. Получаем содержимое страницы

Сначала сделаем веб-запрос к странице новости и получим ее HTML-код:

In [5]:
import requests

In [6]:
url = 'https://lenta.ru/articles/2018/07/01/pobeda/'
r = requests.get(url)

In [7]:
# Проверяем, что запрос прошел удачно, и мы получили код ответа 200:

print(r.status_code)

200


In [8]:
# Посмотрим, что же мы получили в качестве содержимого. Это тяжелочитаемый HTML-код страницы:

print(r.text)

<!DOCTYPE html><html xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://ogp.me/ns#"><head><title>Россия уделала Испанию на чемпионате мира. Вся страна в шоке и ликует: Coцсети: Интернет и СМИ: Lenta.ru</title><meta content="Россия уделала Испанию на чемпионате мира. Вся страна в шоке и ликует: Coцсети: Интернет и СМИ: Lenta.ru" name="title" /><meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<script type="text/javascript">window.NREUM||(NREUM={});NREUM.info={"beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseKey":"66a8d51230","applicationID":"1241738","transactionName":"J19cQUoOWA0ERBoQXhRZUUYXElwOFg==","queueTime":0,"applicationTime":116,"agent":""}</script>
<script type="text/javascript">(window.NREUM||(NREUM={})).loader_config={xpid:"VQUGU1VRGwICUFBVBAk="};window.NREUM||(NREUM={}),__nr_require=function(t,e,n){function r(n){if(!e[n]){var o=e[n]={exports:{}};t[n][0].call(o.exports,function(e){var o=t[n][1][e];return r(o||e)},o,o.exports)}

# Шаг 3. Библиотека BeautifulSoup

Итак, содержимое страницы у нас лежит в r.text. Для того, чтобы извлекать нужную нам информацию, воспользуемся библиотекой BeautifulSoup. Переведем содержимое страницы в объект BeautifulSoup:

In [9]:
from bs4 import BeautifulSoup

In [10]:
soup = BeautifulSoup(r.text, 'html.parser')

In [11]:
# Содержимое переменной soup, на первый взгляд, не отличается от текста страницы:

print(soup)

<!DOCTYPE html>
<html xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://ogp.me/ns#"><head><title>Россия уделала Испанию на чемпионате мира. Вся страна в шоке и ликует: Coцсети: Интернет и СМИ: Lenta.ru</title><meta content="Россия уделала Испанию на чемпионате мира. Вся страна в шоке и ликует: Coцсети: Интернет и СМИ: Lenta.ru" name="title"/><meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<script type="text/javascript">window.NREUM||(NREUM={});NREUM.info={"beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseKey":"66a8d51230","applicationID":"1241738","transactionName":"J19cQUoOWA0ERBoQXhRZUUYXElwOFg==","queueTime":0,"applicationTime":116,"agent":""}</script>
<script type="text/javascript">(window.NREUM||(NREUM={})).loader_config={xpid:"VQUGU1VRGwICUFBVBAk="};window.NREUM||(NREUM={}),__nr_require=function(t,e,n){function r(n){if(!e[n]){var o=e[n]={exports:{}};t[n][0].call(o.exports,function(e){var o=t[n][1][e];return r(o||e)},o,o.exports)}r

In [12]:
#Однако теперь мы можем получать нужные нам элементы страницы, обращаясь к soup. Например, для получения заголовка используем метод title:

soup.title

<title>Россия уделала Испанию на чемпионате мира. Вся страна в шоке и ликует: Coцсети: Интернет и СМИ: Lenta.ru</title>

In [13]:
#Чтобы оставить только текст заголовка без тэгов, добавим text:

soup.title.text

'Россия уделала Испанию на чемпионате мира. Вся\xa0страна в шоке и ликует: Coцсети: Интернет и СМИ: Lenta.ru'

# Шаг 4. Редакторский заголовок

Заголовок из тэга title — это довольно просто. Но как мы видим, на странице реальный заголовок, который видят пользователи, отличается:

Нам потребуется ID этого заголовка на странице. Откройте страницу новости, наведите курсор на заголовок и через правый клик мыши (или нажатие двумя пальцами на тачпаде) откройте меню. Найдите пункт "Исследовать элемент" и откройте его. В Google Chrome и Яндекс.Браузере это будет выглядеть так:

In [14]:
# Все, что нам потребуется, — это название класса class_='b-topic__title' в коде этого элемента. 
# Просто задаем библиотеке BeautifulSoup найти этот элемент:

soup.find(class_='b-topic__title')

<h1 class="b-topic__title" itemprop="headline">«Простите, парни, что поливал вас дерьмом на каждом углу»</h1>

In [15]:
# Или только текст заголовка:

soup.find(class_='b-topic__title').text

'«Простите, парни, что поливал вас дерьмом на\xa0каждом углу»'

# Шаг 5. Дата публикации

Давайте вытащим дату публикации со страницы новости:

Наводим на дату и нажимаем 'Исследовать элемент'. Можно искать по названию класса 'g-date'. Но если на странице несколько элементов с таким названием, то мы можем получить не то, что хотим. Давайте сначала возьмем содержимое элемента class_='b-topic__info' (на скриншоте этот элемент чуть выше выделенной синим строчки на один уровень вложенности выше).

In [16]:
topic = soup.find('div', class_='b-topic__info')
topic

<div class="b-topic__info"><time class="g-date" datetime="2018-07-01T21:20:00+03:00" itemprop="datePublished" pubdate=""> 21:20,  1 июля 2018</time><h1 class="b-topic__title" itemprop="headline">«Простите, парни, что поливал вас дерьмом на каждом углу»</h1><h2 class="b-topic__rightcol">Россия уделала Испанию на чемпионате мира. Вся страна в шоке и ликует</h2><div class="b-topic__socials _header"><div class="b-socials"><div class="b-socials__sharing js-sharing"></div><div class="b-socials__favorite"><div class="b-favorite js-favorite" data-class-active="b-favorite_active" data-class-loaded="b-favorite_loaded" data-class-logged="b-favorite_logged" data-uri="/articles/2018/07/01/pobeda/"><a class="b-favorite__item b-favorite__button js-favorite__button" href="/auth/signin/"><svg class="b-favorite__button-icon svg-icons__ui-shevron b-favorite__icon-shevron"><use xlink:href="#ui-chevron"></use></svg><svg class="b-favorite__button-icon svg-icons__ui-shevron_stroke b-favorite__icon-shevron_st

<div class="b-topic__info">
    <time class="g-date" datetime="2018-07-01T21:20:00+03:00" pubdate="" itemprop="datePublished"> 21:20,  1 июля 2018</time>

Нужная нам дата где-то внутри переменной topic. Зададим теперь поиск внутри topic и получим дату публикации:

In [17]:
topic.find(class_ = 'g-date').text

' 21:20,  1 июля 2018'

# Шаг 6. Текст новости

Искать можно не только по классам, но и по другим атрибутам элементов. Попробуйте самостоятельно найти в коде страницы атрибуты основного текста новости:

<div class="b-text clearfix js-topic__text" itemprop="articleBody">

Теперь можно найти текст новости по значению атрибута itemprop:



In [19]:
soup.find( itemprop = 'articleBody' ).text

'Сборная России обыграла Испанию и вышла в четвертьфинал чемпионата мира по футболу. Многие ждали от встречи с сильнейшей команды планеты хотя бы нестыдной борьбы, а в итоге получили исторический матч — 4:3, результат превзошел все ожидания. Шок, ликование на улицах, а в соцсетях\xa0— пожар, эмоции переполняют болельщиков.Пользователи сети благодарят команду и извиняются перед тренером, в которого еще совсем недавно не верили.\n—\n  милькøш 击 (@lixoradkaenota)\n  01 июля 2018, 16:54\n\n\n\n—\n  созерцатель (@newfag_in_life)\n  01 июля 2018, 16:42\n\n\n\n—\n  Vitaly Petrov (@vitalypetrov)\n  01 июля 2018, 17:02\n\n\n\n—\n  Борисыч (@Borisich_glass)\n  01 июля 2018, 16:54\n\n\n\n—\n  Anton Ziuzenok (@a_ziuzenok)\n  01 июля 2018, 17:16\n\n\n\n—\n  Станислав Рынкевич (@salt1s)\n  01 июля 2018, 16:51\n\n\n\n—\n  Марат Касем (@MaratQasem)\n  01 июля 2018, 17:12\n\n\n\n—\n  Ромыч (@Instigator_88)\n  01 июля 2018, 17:03\n\n\n\n—\n  Milligan (@milligantop)\n  01 июля 2018, 17:03\n\n\nЧемпионат 

# Шаг 7. Ссылки в тексте 

Отдельно рассмотрим поиск ссылок на другие страницы в тексте новости. В самом простом случае ссылка на HTML-странице задается тэгом 'a', у которого в параметре 'href' прописывается текст ссылки: "<a href="https://some_site.ru">"

Зададим поиск по тэгу 'a':

In [20]:
for link in soup.find( itemprop = 'articleBody' ).find_all( 'a' ):
    print( link )

<a href="https://lenta.ru/news/2018/07/01/russia_win/" target="_blank">обыграла</a>
<a href="https://twitter.com/lixoradkaenota/status/1013465983061778433"><time datetime="2018-07-01T16:54:54+00:00">01 июля 2018, 16:54</time></a>
<a href="https://twitter.com/newfag_in_life/status/1013462966782582785"><time datetime="2018-07-01T16:42:55+00:00">01 июля 2018, 16:42</time></a>
<a href="https://twitter.com/vitalypetrov/status/1013467931257311232"><time datetime="2018-07-01T17:02:38+00:00">01 июля 2018, 17:02</time></a>
<a href="https://twitter.com/Borisich_glass/status/1013465759799042048"><time datetime="2018-07-01T16:54:01+00:00">01 июля 2018, 16:54</time></a>
<a href="https://twitter.com/a_ziuzenok/status/1013471409979445249"><time datetime="2018-07-01T17:16:28+00:00">01 июля 2018, 17:16</time></a>
<a href="https://twitter.com/salt1s/status/1013465249989775360"><time datetime="2018-07-01T16:51:59+00:00">01 июля 2018, 16:51</time></a>
<a href="https://twitter.com/MaratQasem/status/1013470

In [21]:
# И теперь просто извлечем значение href из этих ссылок:

for link in soup.find( itemprop = 'articleBody' ).find_all( 'a' ):
    print( link.get('href') )

https://lenta.ru/news/2018/07/01/russia_win/
https://twitter.com/lixoradkaenota/status/1013465983061778433
https://twitter.com/newfag_in_life/status/1013462966782582785
https://twitter.com/vitalypetrov/status/1013467931257311232
https://twitter.com/Borisich_glass/status/1013465759799042048
https://twitter.com/a_ziuzenok/status/1013471409979445249
https://twitter.com/salt1s/status/1013465249989775360
https://twitter.com/MaratQasem/status/1013470315492585474
https://twitter.com/Instigator_88/status/1013468227370962944
https://twitter.com/milligantop/status/1013468156373950464
https://twitter.com/she_lova_/status/1013463135477551108
https://twitter.com/Fall_Out_Daria/status/1013463774253248512
/tags/persons/akinfeev-igor/
https://twitter.com/valyagorushkina/status/1013467293144305665
https://twitter.com/Alisa06101/status/1013466591034511369
https://twitter.com/quad_axels/status/1013469038406701056
https://twitter.com/GuyFloral/status/1013467692601184256
https://twitter.com/maleenkiymyc/st

# Блок 4. Чтение HTML-таблиц в Pandas > Шаг 1. Постановка задачи

При работе с web-страницами было бы здорово получать содержимое их таблиц в виде датафрейма. Рассмотрим страницу Центрального банка РФ. Поскольку она может со временем измениться, то мы будем брать ее HTML-код из файла cbr.html. Тогда вы точно сможете повторить все действия данного блока.

Наша задача будет состоять в том, чтобы получить одну из таблиц виджетов в виде датафрейма. Например, таблицу цен на драгоценные металлы.

# Шаг 2. Простой вариант решения

In [66]:
# Метод read_html умеет автоматически находить на HTML-странице таблицы и возвращать их списком из датафреймов:

from bs4 import BeautifulSoup
import pandas as pd
url = 'http://www.cbr.ru'
r = requests.get(url)
print(r.status_code)

200


In [24]:
print(r.text)


<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- (c) Art. Lebedev Studio | http://www.artlebedev.ru/ -->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="zoom:lang" content="ru" />

        <meta http-equiv="Refresh" content="180" />

    <title>Центральный банк Российской Федерации</title>

    <link rel="apple-touch-icon" sizes="57x57" href="/f/media/favicons/apple-touch-icon-57x57.png" />
    <link rel="apple-touch-icon" sizes="60x60" href="/f/media/favicons/apple-touch-icon-60x60.png" />
    <link rel="apple-touch-icon" sizes="72x72" href="/f/media/favicons/apple-touch-icon-72x72.png" />
    <link rel="apple-touch-icon" sizes="76x76" href="/f/media/favicons/apple-touch-icon-76x76

In [34]:
# Таблица драгоценных металлов оказалась четвертой по счету:
# <h3><i class="toggler ico ico-arrow-fat unselectable"></i><a href="/hd_base/metall/">Учетные цены на драгоценные металлы</a></h3>

pd.read_html(url)[3]

0           1
0  рублей за грамм  06.04.2019
1        Золото Au    2 710,41
2       Серебро Ag        3195
3       Платина Pt    1 909,42
4      Палладий Pd    2 815,77

Если этого не происходит или вы не уверены в том, что порядок таблице на странице неизменен, то можно вручную найти нужную таблицу на странице. Этому случаю посвящены следующие шаги.

# Шаг 3. Получаем код страницы

In [36]:
from bs4 import BeautifulSoup
import pandas as pd

In [40]:
# Читаем содержимое страницы из файла:

soup = BeautifulSoup(open('http://www.cbr.ru/', 'r'), 'html.parser')

OSError: [Errno 22] Invalid argument: 'http://www.cbr.ru/'

In [41]:
soup = BeautifulSoup(r.text, 'html.parser')

# Шаг 4. Ищем виджет на странице

Как и раньше, нажимаем 'Исследовать элемент' в меню браузера на виджете с драгоценными металлами:

In [ ]:
В сохраненной версии страницы виджету соответствует следующий код:

Нам необходимо добраться до кода таблицы, который начинается с тэга <table>. Таблиц на странице много, поэтому детально указываем путь к таблице виджета драгоценных металлов:

In [42]:
data = soup.find(class_='widget type_table name_metal opened').find(class_='content').find('table')

# Шаг 5. Переводим таблицу в датафрейм

Сейчас наша таблица записана в HTML-коде:

<div class="content">
            <table>
              <tbody>
                <tr>
                  <th class="title">рублей за грамм</th>
                  <th>06.04.2019</th>
                </tr>
                <tr>
                  <td class="title">
                      Золото <ins>Au</ins>
                  </td>
                  <td>
                    <div class="w_data_wrap"><span class="nowrap">2 710,41</span></div>
                  </td>
                </tr>
                <tr>
                  <td class="title">
                      Серебро <ins>Ag</ins>
                  </td>
                  <td>
                    <div class="w_data_wrap"><span class="nowrap">31,95</span></div>
                  </td>
                </tr>
                <tr>
                  <td class="title">
                      Платина <ins>Pt</ins>
                  </td>
                  <td>
                    <div class="w_data_wrap"><span class="nowrap">1 909,42</span></div>
                  </td>
                </tr>
                <tr>
                  <td class="title">
                      Палладий <ins>Pd</ins>
                  </td>
                  <td>
                    <div class="w_data_wrap"><span class="nowrap">2 815,77</span></div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

Для перевода ее в датафрейм используем метод read_html. Метод возвращает список датафреймов. В нашем случае датафрейм будет только один, поэтому сразу берем первый элемент:

In [44]:
df = pd.read_html(str(data))[0]
df

0           1
0  рублей за грамм  06.04.2019
1        Золото Au    2 710,41
2       Серебро Ag        3195
3       Платина Pt    1 909,42
4      Палладий Pd    2 815,77

Датафрейм получен! Теперь можно работать с ним средствами Pandas.

# Блок 5. Введение в работу с API ВКонтакте > Шаг 1. Авторизация в API

Перед тем, как познакомиться с API ВКонтакте, необходимо пройти авторизацию, т. к. многие методы требуют сервисного токена. Также мы познакомимся с форматом файлов YAML, который позволяет удобно работать с параметрами скрипта и паролями.

Авторизация применяется практически во всех API, чтобы отдавать данные только их владельцу или контролировать количество запросов в единицу времени. Сервисный токен для нашей задачи создается вместе с новым приложением. Приложение мы делать, конечно, не будем. Оно нужно только для получения токена, чтобы сделать необходимые выгрузки.

Зайдите на страницу https://vk.com/editapp?act=create, чтобы создать приложение (вы должны быть авторизованы ВКонтакте). Дайте приложению любое название и оставьте значение платформы "Standalone-приложение":

После подтверждения создания приложения в приложении ВК или по СМС зайдите в настройки:

Нужный нам токен лежит в поле "Сервисный ключ доступа".

ФОРМАТ YAML

Теперь необходимо передавать этот ключ с каждым запросом с методом wall.get. Возникает проблема: как хранить этот ключ? Просто записать его в переменную в коде — не лучшая идея.

Это относится вообще к любым токенам, паролям, ключам и другой чувствительной информации, по крайней мере, по двум причинам:

При отправке кому-либо файла с кодом или сохранении в другом месте ваш ключ может быть доступен другому человеку. Еще хуже, если вы случайно сохраните его на общем сетевом диске или открытом репозитории на Github.
Ключ, который продолжительное время виден на вашем экране (пока вы пишете код), также не добавляет безопасности вашему приложению.
Для частичного решения этих проблем, а также хранения внешних переменных вне кода, был разработан формат YAML. 

Он позволяет записывать ваши переменные и их значения в файл, а затем импортировать их в код в JSON-формате. Это гораздо удобнее, чем читать обычный файл построчно и доставать из него нужные вам строки. Также в YAML-файлах можно оставлять комментарии к параметрам.

Т. е. отличие YAML-формата от обычного текстового файла в том, что Python (и другие языки программирования) может распознавать его содержимое как словарь.

Файл config_example.yaml

Рассмотрим пример чтения YAML-файла config_example.yaml. Содержимое файла (файл открыт в редакторе Sublime Text):

In [3]:
# В питоне для чтения YAML-файлов использовать стандарную библиотеку yaml:
from yaml import load

In [4]:
f = open('config_example.yaml', mode = 'r', encoding = 'utf-8')
config = load(f)

In [5]:
#Посмотрим содержимое переменной config:

print(config)

{'access_token': 'g6434uqghoq374gh3qh38ry24orh24h3rjg03q', 'mysql': {'host': '10.0.108.8', 'port': 3306, 'database': 'scoring', 'user': 'defaultuser', 'password': 'passw@rd'}, 'cities': ['Москва', 'Санкт-Петербург', 'Волгоград', 'Новороссийск', 'Тула', 'Мурманск', 'Смоленск', 'Севастополь', 'Одесса', 'Киев', 'Керчь', 'Минск']}


In [6]:
# В нем для примера содержится пример ключ-значение для хранения единичного значения. Для импорта токена с кодом достаточно написать:

token = config['access_token']
print(token)

g6434uqghoq374gh3qh38ry24orh24h3rjg03q


In [48]:
# Второй пример — хранение конфигураций подключения к базе данных в виде словаря. Параметры импортируются аналогично:

database_host = config['mysql']['host']
print(database_host)

10.0.108.8


In [49]:
# Третий пример — хранение списка значений в виде обычного листа:

print(config['cities'])

['Москва', 'Санкт-Петербург', 'Волгоград', 'Новороссийск', 'Тула', 'Мурманск', 'Смоленск', 'Севастополь', 'Одесса', 'Киев', 'Керчь', 'Минск']


СОЗДАЙТЕ КЛЮЧ ДОСТУПА

Создайте файл config.yaml и запишите в него сервисный токен вашего приложения ВКонтакте. Используйте ключ 'access_token' как в примере, далее в коде мы будем использовать такое обозначение.

у меня access_token (Сервисный ключ доступа) = 11c6d63d11c6d63d11c6d63dca11af072a111c611c6d63d4d6dfb3e39eb0b29f3baf6b0

Защищённый ключ = uLuvTOnL7X2zrhQw8MES

In [159]:
token = 'd4b67cd4d4b67cd4d4b67cd4ced4dfadacdd4b6d4b67cd4881d441845cd205888a5e499'

ТАК РАБОТАЕТ!
https://api.vk.com/method/users.get?user_id=1&v=5.52&access_token=d4b67cd4d4b67cd4d4b67cd4ced4dfadacdd4b6d4b67cd4881d441845cd205888a5e499

{"response":[{"id":1,"first_name":"Pavel","last_name":"Durov"}]}

https://api.vk.com/method/users.get?user_id=1&v=5.52&fields=sex,bdate&access_token=d4b67cd4d4b67cd4d4b67cd4ced4dfadacdd4b6d4b67cd4881d441845cd205888a5e499

{"response":[{"id":1,"first_name":"Pavel","last_name":"Durov","sex":2,"bdate":"10.10.1984"}]}

# Шаг 2. Основные понятия API

В прошлом блоке мы рассматривали получение данных сайтов из HTML-страниц, что во многих случаях неудобно. К счастью, многие системы имеют специальный интерфейс для забора данных программным способом с помощью API.

API (application programming interface) — набор методов и параметров, которые позволяют отдавать структурированную информацию по запросу.

В этом блоке мы изучим работу API ВКонтакте на открытых данных — это один из самых простых API.

В итоге мы научимся получать данные для статистических отчетов произвольной группы, например:

соотношение мужчин и женщин в группе;
статистика географии пользователей;
другие данные для аналитики групп конкурентов.
Но сначала рассмотрим работу API на простом примере, на основе которого работают многие системы. 

Перейдите по следующей ссылке в браузере, подставив сервисный токен из прошлого шага:

https://api.vk.com/method/users.get?user_id=1&v=5.52&access_token=token


https://api.vk.com/method/users.get?user_id=1&v=5.52&access_token='g6434uqghoq374gh3qh38ry24orh24h3rjg03q'
Результат:

{"response":[{"id":1,"first_name":"Павел","last_name":"Дуров"}]}

Сейчас мы сделали GET-запрос к API ВКонтакте, который состоит из следующих частей:

https://api.vk.com/method — домен и URL запроса API. Обычно не меняется.

users.get — название метода, который отдает определенный отчет. В нашем случае это метод для получения информации о пользователе.

user_id и v — параметры запроса: идентификатор пользователя, о котором хотим получить информацию, и номер версии API.
Данный метод не требует авторизации в системе, поскольку эти данные являются открытыми.

Однако очень часто запросы к API требуют авторизационного токена, о них мы поговорим позже. Токен выдается только тем пользователям, которые имеют право просматривать определенные данные. Например, показания счетчиков Яндекс.Метрики вашего проекта.

На все остальные запросы без корректного токена система отвечает отказом.

Если мы посмотрим документацию метода users.get, то увидим, что в ней описано множество других параметров, которые можно получить о пользователе: дата рождения, пол, родной город и другие.

Т. е. все то, что мы видим на странице пользователя в интерфейсе или приложении ВКонтакте (конечно, если пользователь их указал). Добавим к запросу дату рождения и пол (согласно документации, эти параметры надо перечислять в поле fields):

https://api.vk.com/method/users.get?user_id=1&v=5.52&fields=sex,bdate&access_token=token

Результат:

{"response":[{"id":1,"first_name":"Павел","last_name":"Дуров","sex":2,"bdate":"10.10.1984"}]}

Примечание: значение 2 у параметра 'sex' означает мужской пол.

### Упражнение

Какое значение ID у страны, указанной в профиле Павла Дурова (ID отдается вместе с названием страны)? Укажите ответ в виде целого числа.

# Шаг 3. Запросы к API из кода

Мы делали все запросы в браузере. Давайте реализуем аналогичные запросы в коде.

Для запросов используем ту же библиотеку requests:

Теперь, помимо URL запроса (https://api.vk.com...), нам надо указывать его параметры (user_id, fields и другие). Создадим для этого словарь params:

In [185]:
import requests

In [186]:
params = {
    'user_id': 1,
    'v': 5.52,
    'fields': 'city,sex,bdate'
}

In [187]:
url = 'https://api.vk.com/method/users.get?user_id=1&v=5.52&fields=sex,bdate&access_token=d4b67cd4d4b67cd4d4b67cd4ced4dfadacdd4b6d4b67cd4881d441845cd205888a5e499'
r = requests.get(url)
print(r.status_code)

200


In [188]:
# Отправим запрос с параметрами и посмотрим, что получили в ответ:

r = requests.get(url, params = params)
r.text

u'{"response":[{"id":1,"first_name":"Pavel","last_name":"Durov","sex":2,"bdate":"10.10.1984","city":{"id":2,"title":"Saint Petersburg"}}]}'

Результат:

'{"response":[{"id":1,"first_name":"Павел","last_name":"Дуров","sex":2,"bdate":"10.10.1984"}]}'

Мы получили ответ в формате JSON (https://ru.wikipedia.org/wiki/JSON). Этот формат представляет собой набор вложенных словарей и листов, к которым очень удобно обращаться при обработке ответа. JSON применяется в подавляющем большинстве систем с API, т. к. намного проще и удобнее, чем его предшественник — формат XML.

Для улучшения читаемости можно воспользоваться библиотекой pprint. Она сильно помогает читать JSON-формат для больших ответов.

In [189]:
from pprint import pprint

In [190]:
data = r.json()

In [191]:
pprint(data)

{u'response': [{u'bdate': u'10.10.1984',
                u'city': {u'id': 2, u'title': u'Saint Petersburg'},
                u'first_name': u'Pavel',
                u'id': 1,
                u'last_name': u'Durov',
                u'sex': 2}]}


Получим из этого запроса дату рождения. Для этого надо сначала обратиться к ключу response:

In [192]:
data['response']

[{u'bdate': u'10.10.1984',
  u'city': {u'id': 2, u'title': u'Saint Petersburg'},
  u'first_name': u'Pavel',
  u'id': 1,
  u'last_name': u'Durov',
  u'sex': 2}]

In [193]:
# Теперь обращаемся к получившемуся листу из одного элемента:

data['response'][0]

{u'bdate': u'10.10.1984',
 u'city': {u'id': 2, u'title': u'Saint Petersburg'},
 u'first_name': u'Pavel',
 u'id': 1,
 u'last_name': u'Durov',
 u'sex': 2}

In [194]:
# И, наконец, берем ключ 'bdate':

birthday = data['response'][0]['bdate']
print(birthday)

# Ответ: 10.10.1984

10.10.1984


In [195]:
city_1 = data['response'][0]['city']
print(city_1)

{u'id': 2, u'title': u'Saint Petersburg'}


### Упражнение

Имеется набор ID пользователей users. Необходимо посчитать какую долю этих пользователей составляют женщины. Не учитывайте пользователей, у которых пол не указан. Пример формата ответа: 0.35.

Ниже в качестве подсказки приведены первые шаги в решении задачи. Но сначала попробуйте справиться сами, так интереснее!

In [170]:
users = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [171]:
# НАЧАЛО РЕШЕНИЯ
# Начнем с цикла запросов к API ВКонтакте:

for user in users:
    params = {
        'user_id': user,
        'v': 5.52,
        'fields': 'sex,bdate,city',
        'access_token': token
    }   
    r = requests.get(url, params = params)
    print(r.json())

{u'response': [{u'city': {u'id': 2, u'title': u'Saint Petersburg'}, u'first_name': u'Pavel', u'bdate': u'10.10.1984', u'sex': 2, u'last_name': u'Durov', u'id': 1}]}
{u'response': [{u'first_name': u'Alexandra', u'last_name': u'Vladimirova', u'id': 2, u'sex': 1}]}
{u'response': [{u'deactivated': u'deleted', u'first_name': u'DELETED', u'last_name': u'', u'id': 3, u'sex': 0}]}
{u'response': [{u'deactivated': u'deleted', u'first_name': u'DELETED', u'last_name': u'', u'id': 4, u'sex': 0}]}
{u'response': [{u'city': {u'id': 1, u'title': u'Moscow'}, u'first_name': u'Ilya', u'bdate': u'18.11', u'sex': 2, u'last_name': u'Perekopsky', u'id': 5}]}
{u'response': [{u'city': {u'id': 2, u'title': u'Saint Petersburg'}, u'first_name': u'Nikolay', u'last_name': u'Durov', u'id': 6, u'sex': 2}]}
{u'response': [{u'city': {u'id': 295, u'title': u'London'}, u'first_name': u'Alexey', u'last_name': u'Kobylyansky', u'id': 7, u'sex': 2}]}
{u'response': [{u'city': {u'id': 314, u'title': u'Kyiv'}, u'first_name': u'A

Результат:

{'response': [{'id': 1, 'first_name': 'Павел', 'last_name': 'Дуров', 'sex': 2, 'bdate': '10.10.1984'}]}

{'response': [{'id': 2, 'first_name': 'Александра', 'last_name': 'Владимирова', 'sex': 1, 'hidden': 1}]}

{'response': [{'id': 3, 'first_name': 'DELETED', 'last_name': '', 'deactivated': 'deleted', 'sex': 0}]}

{'response': [{'id': 4, 'first_name': 'DELETED', 'last_name': '', 'deactivated': 'deleted', 'sex': 0}]}

{'response': [{'id': 5, 'first_name': 'Илья', 'last_name': 'Перекопский', 'sex': 2, 'bdate': '18.11'}]}

{'response': [{'id': 6, 'first_name': 'Николай', 'last_name': 'Дуров', 'sex': 2, 'hidden': 1}]}

{'response': [{'id': 7, 'first_name': 'Алексей', 'last_name': 'Кобылянский', 'sex': 2, 'hidden': 1}]}

{'response': [{'id': 8, 'first_name': 'Аки', 'last_name': 'Сепиашвили', 'sex': 2}]}

{'response': [{'id': 9, 'first_name': 'Настя', 'last_name': 'Васильева', 'sex': 1}]}

{'response': [{'id': 10, 'first_name': 'Александр', 'last_name': 'Кузнецов', 'sex': 2}]}

Вам необходимо дописать алгоритм, чтобы посчитать долю пользователей с sex = 1 среди всех пользователей со значением sex 1 или 2.

# Блок 6. Статистика пользователей группы > Шаг 1. Ограничения API

В текущем шаге мы научимся работать с двумя ограничениями, которые свойственны практически всем системам:

ограничение на количество вызовов в единицу времени;
ограничение на количество выгружаемых строк за один запрос.
Ограничение на количество запросов в секунду сделано для того, чтобы избежать чрезмерной нагрузки на сервера системы. И в ряде случаев небольшое количество отчетов можно выгрузить, уложившись в этот лимит (например, как мы получили информацию о 10 пользователях в прошлом упражнении). Однако второе ограничение не удастся «обойти» в случае выгрузки больших отчетов. Например, чтобы получить список всех пользователей очень популярной группы, серверу, возможно, придется отправить вам разом лист из миллионов записей.

Давайте рассмотрим, как работать с этими ограничениями на примере выгрузки списка пользователей группы https://vk.com/habr.

Для получения списка пользователей группы воспользуемся методом groups.getMembers: https://vk.com/pages?oid=-1&p=groups.getMembers.

Согласно документации, обязательным параметром является ID или короткое имя группы. В нашем случае это habr: https://vk.com/habr. Тестируем, как работает метод в самом простом случае:

In [196]:
import requests
url = 'https://api.vk.com/method/groups.getMembers'
params = {
    'group_id': 'habr',
    'v': 5.73,
    'fields': 'sex,bdate,city',
    'access_token': token
}
r = requests.get(url, params = params)
data = r.json()
print(data)

{u'response': {u'count': 802848, u'items': [{u'city': {u'id': 2, u'title': u'Saint Petersburg'}, u'first_name': u'Nikolay', u'last_name': u'Durov', u'id': 6, u'sex': 2}, {u'city': {u'id': 2, u'title': u'Saint Petersburg'}, u'first_name': u'Alexander', u'last_name': u'Kuznetsov', u'id': 10, u'sex': 2}, {u'city': {u'id': 2, u'title': u'Saint Petersburg'}, u'first_name': u'Mikhail', u'bdate': u'18.12', u'sex': 2, u'last_name': u'Petrov', u'id': 11}, {u'city': {u'id': 2, u'title': u'Saint Petersburg'}, u'first_name': u'Alexander', u'bdate': u'21.10.1982', u'sex': 2, u'last_name': u'Bespalov', u'id': 17}, {u'city': {u'id': 2, u'title': u'Saint Petersburg'}, u'first_name': u'Rammi', u'bdate': u'11.5.1986', u'sex': 2, u'last_name': u'Tsitsuashvili', u'id': 24}, {u'city': {u'id': 2, u'title': u'Saint Petersburg'}, u'first_name': u'Tatyana', u'bdate': u'2.6', u'sex': 1, u'last_name': u'Plutalova', u'id': 34}, {u'deactivated': u'banned', u'first_name': u'Gabriel', u'last_name': u'Shalel', u'id':

In [197]:
import requests
url = 'https://api.vk.com/method/groups.getMembers'
params = {
    'group_id': 'habr',
    'v': 5.73,
    'access_token': token
}
r = requests.get(url, params = params)
data = r.json()
print(data)

{u'response': {u'count': 802847, u'items': [6, 10, 11, 17, 24, 34, 47, 55, 57, 161, 169, 239, 243, 251, 341, 345, 347, 348, 404, 409, 453, 478, 480, 485, 488, 489, 510, 512, 530, 550, 591, 616, 619, 628, 630, 634, 669, 687, 702, 718, 720, 804, 834, 880, 885, 891, 905, 914, 952, 966, 975, 979, 982, 985, 1004, 1010, 1038, 1091, 1097, 1109, 1127, 1139, 1159, 1174, 1198, 1200, 1211, 1215, 1242, 1278, 1331, 1338, 1346, 1351, 1381, 1473, 1479, 1481, 1496, 1500, 1507, 1523, 1544, 1583, 1587, 1615, 1624, 1632, 1644, 1667, 1668, 1690, 1697, 1699, 1708, 1710, 1721, 1736, 1754, 1772, 1786, 1794, 1814, 1828, 1829, 1834, 1835, 1839, 1843, 1857, 1860, 1867, 1880, 1906, 1946, 1964, 1967, 2008, 2019, 2050, 2051, 2075, 2103, 2131, 2150, 2176, 2206, 2209, 2229, 2230, 2281, 2284, 2298, 2310, 2322, 2341, 2373, 2389, 2395, 2407, 2410, 2461, 2463, 2472, 2484, 2492, 2539, 2541, 2542, 2592, 2609, 2615, 2619, 2622, 2635, 2658, 2693, 2718, 2720, 2722, 2729, 2752, 2756, 2758, 2821, 2827, 2832, 2871, 2911, 2914, 

In [173]:
k = [6, 10, 11, 17, 24, 34, 47, 55, 57, 161, 169, 239, 243, 251, 341, 345, 347, 348, 404, 409, 453, 478, 480, 485, 488, 489, 510, 512, 530, 550, 591, 616, 619, 628, 630, 634, 669, 687, 702, 718, 720, 804, 834, 880, 885, 891, 905, 914, 952, 966, 975, 979, 982, 985, 1004, 1010, 1038, 1091, 1097, 1109, 1127, 1139, 1159, 1174, 1198, 1200, 1211, 1215, 1242, 1278, 1331, 1338, 1346, 1351, 1381, 1473, 1479, 1481, 1496, 1500, 1507, 1523, 1544, 1583, 1587, 1615, 1624, 1632, 1644, 1667, 1668, 1690, 1697, 1699, 1708, 1710, 1721, 1736, 1754, 1772, 1786, 1794, 1814, 1828, 1829, 1834, 1835, 1839, 1843, 1857, 1860, 1867, 1880, 1906, 1946, 1964, 1967, 2008, 2019, 2050, 2051, 2075, 2103, 2131, 2150, 2176, 2206, 2209, 2229, 2230, 2281, 2284, 2298, 2310, 2322, 2341, 2373, 2389, 2395, 2407, 2410, 2461, 2463, 2472, 2484, 2492, 2539, 2541, 2542, 2592, 2609, 2615, 2619, 2622, 2635, 2658, 2693, 2718, 2720, 2722, 2729, 2752, 2756, 2758, 2821, 2827, 2832, 2871, 2911, 2914, 2932, 2933, 2946, 2981, 2983, 3006, 3020, 3050, 3073, 3100, 3110, 3151, 3153, 3161, 3226, 3250, 3254, 3259, 3300, 3304, 3328, 3377, 3402, 3407, 3412, 3420, 3422, 3427, 3443, 3450, 3486, 3491, 3516, 3523, 3548, 3597, 3644, 3646, 3647, 3653, 3674, 3688, 3697, 3707, 3756, 3768, 3803, 3851, 3864, 3894, 3897, 3909, 3972, 4000, 4021, 4026, 4041, 4047, 4080, 4092, 4107, 4169, 4188, 4234, 4262, 4265, 4282, 4310, 4318, 4377, 4439, 4463, 4468, 4525, 4528, 4564, 4566, 4596, 4615, 4625, 4640, 4669, 4681, 4689, 4695, 4718, 4731, 4735, 4737, 4742, 4761, 4762, 4767, 4773, 4774, 4837, 4857, 4862, 4892, 4917, 4921, 4925, 4944, 4967, 4973, 4996, 5047, 5081, 5102, 5113, 5170, 5172, 5224, 5233, 5245, 5262, 5280, 5282, 5319, 5342, 5362, 5381, 5394, 5401, 5430, 5431, 5460, 5530, 5543, 5546, 5585, 5665, 5715, 5716, 5733, 5794, 5797, 5805, 5818, 5821, 5846, 5876, 5884, 5892, 5896, 5916, 5917, 5923, 5932, 5936, 5944, 5945, 5951, 5957, 5962, 6000, 6021, 6102, 6147, 6157, 6159, 6167, 6181, 6184, 6187, 6227, 6251, 6255, 6260, 6293, 6309, 6333, 6353, 6364, 6455, 6456, 6474, 6477, 6478, 6503, 6542, 6547, 6559, 6592, 6604, 6669, 6683, 6700, 6701, 6707, 6719, 6724, 6781, 6847, 6855, 6862, 6881, 6932, 6980, 6995, 7012, 7014, 7037, 7040, 7061, 7068, 7096, 7179, 7202, 7208, 7210, 7227, 7276, 7308, 7323, 7414, 7468, 7488, 7525, 7528, 7542, 7557, 7584, 7609, 7628, 7701, 7712, 7718, 7740, 7750, 7764, 7770, 7799, 7833, 7837, 7840, 7842, 7846, 7901, 7905, 7983, 8076, 8085, 8097, 8131, 8147, 8149, 8157, 8163, 8172, 8191, 8200, 8209, 8244, 8266, 8273, 8297, 8298, 8323, 8332, 8338, 8346, 8351, 8373, 8406, 8418, 8422, 8426, 8485, 8486, 8490, 8495, 8571, 8614, 8618, 8651, 8653, 8670, 8684, 8704, 8716, 8767, 8784, 8788, 8799, 8808, 8823, 8829, 8875, 8882, 8910, 8913, 8921, 8930, 8943, 8985, 9000, 9020, 9022, 9028, 9040, 9088, 9106, 9127, 9155, 9214, 9243, 9266, 9316, 9319, 9331, 9355, 9396, 9399, 9410, 9412, 9416, 9427, 9429, 9435, 9456, 9459, 9463, 9473, 9491, 9499, 9508, 9532, 9545, 9558, 9571, 9574, 9579, 9611, 9631, 9645, 9650, 9660, 9671, 9741, 9773, 9811, 9847, 9850, 9890, 9900, 9927, 10040, 10070, 10087, 10097, 10107, 10135, 10138, 10145, 10217, 10245, 10254, 10302, 10310, 10326, 10360, 10389, 10476, 10480, 10496, 10518, 10549, 10566, 10598, 10612, 10672, 10680, 10705, 10741, 10859, 10916, 10917, 10919, 10926, 10969, 10977, 10999, 11012, 11081, 11106, 11108, 11224, 11232, 11265, 11303, 11563, 11579, 11592, 11631, 11641, 11646, 11713, 11786, 11816, 11848, 11858, 11883, 12005, 12010, 12022, 12027, 12053, 12073, 12079, 12087, 12107, 12125, 12133, 12159, 12231, 12244, 12252, 12325, 12345, 12353, 12394, 12405, 12407, 12424, 12435, 12454, 12456, 12460, 12482, 12502, 12545, 12602, 12608, 12614, 12615, 12620, 12627, 12643, 12680, 12693, 12707, 12715, 12728, 12748, 12762, 12770, 12788, 12805, 12808, 12825, 12847, 12876, 12880, 12892, 12934, 12946, 12952, 12977, 12979, 13008, 13042, 13053, 13085, 13135, 13158, 13161, 13164, 13218, 13283, 13338, 13357, 13362, 13370, 13371, 13404, 13483, 13484, 13506, 13511, 13522, 13584, 13636, 13658, 13664, 13682, 13686, 13706, 13760, 13811, 13822, 13832, 13840, 13843, 13858, 13865, 13894, 13903, 13907, 13933, 13935, 13991, 14006, 14047, 14057, 14099, 14112, 14137, 14228, 14238, 14255, 14259, 14267, 14279, 14280, 14337, 14388, 14440, 14446, 14460, 14487, 14517, 14521, 14545, 14572, 14573, 14688, 14703, 14708, 14718, 14723, 14732, 14764, 14804, 14838, 14842, 14854, 14858, 14866, 14868, 14870, 14882, 14895, 14901, 14908, 14916, 14920, 14922, 14933, 14951, 14953, 15017, 15042, 15077, 15078, 15087, 15121, 15131, 15190, 15221, 15232, 15236, 15303, 15413, 15460, 15481, 15485, 15491, 15537, 15544, 15574, 15580, 15588, 15603, 15616, 15700, 15725, 15776, 15789, 15833, 15839, 15857, 15874, 15884, 15892, 15928, 16017, 16049, 16057, 16064, 16154, 16159, 16211, 16242, 16250, 16253, 16318, 16344, 16404, 16435, 16450, 16452, 16474, 16608, 16643, 16698, 16757, 16894, 16914, 16932, 16955, 16996, 17043, 17049, 17053, 17057, 17064, 17093, 17118, 17166, 17178, 17187, 17212, 17287, 17319, 17338, 17376, 17394, 17403, 17437, 17461, 17502, 17556, 17582, 17583, 17589, 17621, 17624, 17656, 17659, 17689, 17694, 17711, 17830, 17859, 17864, 17870, 17876, 17907, 17944, 17970, 17979, 17987, 18035, 18094, 18101, 18110, 18146, 18185, 18191, 18239, 18257, 18266, 18288, 18295, 18305, 18311, 18312, 18358, 18407, 18455, 18510, 18529, 18546, 18581, 18623, 18632, 18645, 18657, 18658, 18660, 18694, 18712, 18715, 18733, 18735, 18739, 18762, 18773, 18783, 18784, 18787, 18798, 18805, 18820, 18882, 18884, 18892, 18934, 18939, 18944, 18969, 18982, 18994, 19003, 19024, 19042, 19064, 19068, 19089, 19107, 19123, 19203, 19232, 19240, 19293, 19308, 19326, 19331, 19341, 19344, 19381, 19386, 19388, 19399, 19430, 19445, 19504, 19553, 19571, 19583, 19584, 19596, 19611, 19691, 19696, 19702, 19716, 19720, 19755, 19783, 19822, 19890, 19892, 19903, 19959, 20005, 20012, 20016, 20020, 20033, 20045, 20047, 20075, 20078, 20095, 20142, 20149, 20152, 20162, 20163, 20233, 20303, 20347, 20471, 20510, 20551, 20591, 20718, 20724, 20732, 20746, 20752, 20780, 20791, 20797, 20850, 20875, 20919, 20990, 20992, 21034, 21038, 21054, 21077, 21080, 21111, 21123, 21131, 21144, 21163, 21166, 21267, 21278, 21287, 21309, 21348, 21378, 21383, 21401, 21417, 21431, 21445, 21495, 21508, 21528, 21537, 21538, 21551, 21552, 21558, 21628, 21653, 21656, 21675, 21809, 21829, 21846, 21851, 21880, 21902, 21908, 21911, 21916, 21917, 21933, 21997, 22014, 22101, 22106]

In [174]:
len(k)

1000

### Упражнение

Каким из перечисленных способов можно посчитать количество пользователей в data, у которых ID больше 1000?

 len([x['response']['items'] for x in data if x > 1000])
 
 len([x for x in data['response'] if x['items'] > 1000])
 
 len([x for x in data['response']['items'] if x > 1000])

In [100]:
len([x['response']['items'] for x in data if x > 1000])

TypeError: '>' not supported between instances of 'str' and 'int'

In [101]:
len([x for x in data['response'] if x['items'] > 1000])

TypeError: string indices must be integers

In [175]:
len([x for x in data['response']['items'] if x > 1000])

1000

### ВЫГРУЗКА ЛЮБОГО КОЛИЧЕСТВА ПОЛЬЗОВАТЕЛЕЙ
Мы получили первую тысячу пользователей группы. Судя по описанию параметра count в документации, это максимум, который может отдать API за раз.

Для получения следующей тысячи пользователей воспользуемся параметрами count и offset: будем в цикле выгружать по 1000 пользователей (count будет всегда равен 1000), а в каждом следующем шаге цикла увеличим смещение offset на величину count.

Сначала напишем цикл выгрузки первых 20 пользователей со значением count = 5. Т. е. цикл будет выгружать за 1 запрос по 5 пользователей, пока не выгрузит первые 20. Это позволит нам проверить корректность работы цикла перед тем, как делать большие и долгие выгрузки.

Давайте выведем на экран первые 20 пользователей из нашей первой попытки с 1000 пользователей, чтобы было с чем сверить результат выгрузки из 20 пользователей:

In [198]:
users_for_checking = data['response']['items'][:20]
print(users_for_checking)

[6, 10, 11, 17, 24, 34, 47, 55, 57, 161, 169, 239, 243, 251, 341, 345, 347, 348, 404, 409]


In [199]:
# Задаем начальные значения параметров count и offset:

count = 5
offset = 0
url = 'https://api.vk.com/method/groups.getMembers'

In [200]:
# Цикл будет работать до тех пор, пока не выгрузим 20 пользователей. Результат будем писать в лист user_ids:

count = 5
offset = 0
user_ids = []
while offset < 20:
    print('Выгружаю {} пользователей с offset = {}'.format(count, offset))   
    params = {
        'group_id': 'habr',
        'v': 5.73,
        'count': count,
        'offset': offset,
        'fields': 'sex,bdate,city',
        'access_token': token
    }   
    # такой же запрос как в прошлый раз
    r = requests.get(url, params = params)
    data = r.json()   
    user_ids += data['response']['items'] 

    # увеличиваем смещение на количество строк выгрузки
    offset += count

Выгружаю 5 пользователей с offset = 0
Выгружаю 5 пользователей с offset = 5
Выгружаю 5 пользователей с offset = 10
Выгружаю 5 пользователей с offset = 15


In [201]:
print(user_ids)

[{u'city': {u'id': 2, u'title': u'Saint Petersburg'}, u'first_name': u'Nikolay', u'last_name': u'Durov', u'id': 6, u'sex': 2}, {u'city': {u'id': 2, u'title': u'Saint Petersburg'}, u'first_name': u'Alexander', u'last_name': u'Kuznetsov', u'id': 10, u'sex': 2}, {u'city': {u'id': 2, u'title': u'Saint Petersburg'}, u'first_name': u'Mikhail', u'bdate': u'18.12', u'sex': 2, u'last_name': u'Petrov', u'id': 11}, {u'city': {u'id': 2, u'title': u'Saint Petersburg'}, u'first_name': u'Alexander', u'bdate': u'21.10.1982', u'sex': 2, u'last_name': u'Bespalov', u'id': 17}, {u'city': {u'id': 2, u'title': u'Saint Petersburg'}, u'first_name': u'Rammi', u'bdate': u'11.5.1986', u'sex': 2, u'last_name': u'Tsitsuashvili', u'id': 24}, {u'city': {u'id': 2, u'title': u'Saint Petersburg'}, u'first_name': u'Tatyana', u'bdate': u'2.6', u'sex': 1, u'last_name': u'Plutalova', u'id': 34}, {u'deactivated': u'banned', u'first_name': u'Gabriel', u'last_name': u'Shalel', u'id': 47, u'sex': 2}, {u'city': {u'id': 1, u'tit

In [202]:
# Проверим, что выгрузка первых 20 пользователей совпала с листом users_for_checking:

users_for_checking == user_ids

False

Теперь мы можем выгрузить любое количество пользователей, установив значение count в максимальное значение (1000) и поставив в условии цикла while нужное значение.

### Упражнение

Выставлять максимальное значение offset для каждой группы довольно неудобно. Наверняка при использовании значения параметра Offset, превышающего число участников в группе, API ВКонтакте отдает какой-нибудь особенный ответ. Который можно использовать в качестве выхода из цикла запросов. Сделайте запрос методом groups.getMembers с параметром offset, превышаюшим текущее количество участников группы Хабра. Что вы получите в качестве значения ключа 'users'?

'count': 0  
[0]  

пустой лист  

такой запрос всегда отдает ошибку из списка https://vk.com/dev/errors

# Шаг 2. Ограничение по запросам в секунду

Осталась еще одна проблема, описанная в документации в разделе "3.1. Частотные ограничения" (https://vk.com/dev/api_requests). Чтобы не делать запросы к API слишком часто, можем искусственно замедлять выгрузку. Например, после каждого запроса делать паузу, чтобы уложиться в лимит 3 запроса в секунду. Воспользуемся библиотекой time и методом sleep (пауза в 0.5 секунды добавлена в конце цикла):

In [3]:
import time

In [184]:
# Выгрузим первые 10 тысяч пользователей:

count = 1000
offset = 0
user_ids = []
while offset < 10000:
    print('Выгружаю {} пользователей с offset = {}'.format(count, offset))   
    params = {
        'group_id': 'habr',
        'v': 5.73,
        'count': count,
        'offset': offset,
        'fields': 'sex,bdate,city',
        'access_token': token
    }  
    # такой же запрос, как в прошлый раз
    r = requests.get(url, params = params)
    data = r.json()   
    user_ids += data['response']['items']  

    # увеличиваем смещение на количество строк выгрузки
    offset += count
  
    print('Ожидаю 0.5 секунды...')
#    time.sleep(0.5)

Выгружаю 1000 пользователей с offset = 0


TypeError: list indices must be integers, not unicode

### СТАТИСТИКА ПО ГОРОДАМ
Таким способом можно выгрузить пользователей любой группы (при наличии достаточного времени).

Давайте решим следующую задачу: необходимо построить распределение пользователей по городам. Используем возможность метода users.get без авторизации выгрузки сразу 100 пользователей. Пример выгрузки информации о пользователях с ID 1, 2 и 3 одним запросом:

In [180]:
url = 'https://api.vk.com/method/users.get'
params = {
    'user_ids': '1,2,3',
    'v': 5.73,
    'fields': 'sex,bdate,city',
    'access_token': token
}
from pprint import pprint
data = requests.get(url, params = params)
pprint(data.json())

{u'response': [{u'bdate': u'10.10.1984',
                u'city': {u'id': 2, u'title': u'Saint Petersburg'},
                u'first_name': u'Pavel',
                u'id': 1,
                u'last_name': u'Durov',
                u'sex': 2},
               {u'first_name': u'Alexandra',
                u'id': 2,
                u'last_name': u'Vladimirova',
                u'sex': 1},
               {u'deactivated': u'deleted',
                u'first_name': u'DELETED',
                u'id': 3,
                u'last_name': u'',
                u'sex': 0}]}


Итого необходимо взять список пользователей группы, разбить их на группы по 100 человек и для каждой такой группы узнать распределение по городам. Для экономии времени возьмем не 10 тысяч пользователей, а только первые 1000.

Если есть лист 1000 пользователей user_ids, то разбить его на 10 листов user_lists по 100 человек можно следующим образом:

In [181]:
rows_limit = 100
user_lists = []
position = 0
while position < len(user_ids):
    user_lists.append( user_ids[position:position + rows_limit] )
    position += rows_limit

In [182]:
user_lists

[[{u'city': {u'id': 2, u'title': u'Saint Petersburg'},
   u'first_name': u'Nikolay',
   u'id': 6,
   u'last_name': u'Durov',
   u'sex': 2},
  {u'city': {u'id': 2, u'title': u'Saint Petersburg'},
   u'first_name': u'Alexander',
   u'id': 10,
   u'last_name': u'Kuznetsov',
   u'sex': 2},
  {u'bdate': u'18.12',
   u'city': {u'id': 2, u'title': u'Saint Petersburg'},
   u'first_name': u'Mikhail',
   u'id': 11,
   u'last_name': u'Petrov',
   u'sex': 2},
  {u'bdate': u'21.10.1982',
   u'city': {u'id': 2, u'title': u'Saint Petersburg'},
   u'first_name': u'Alexander',
   u'id': 17,
   u'last_name': u'Bespalov',
   u'sex': 2},
  {u'bdate': u'11.5.1986',
   u'city': {u'id': 2, u'title': u'Saint Petersburg'},
   u'first_name': u'Rammi',
   u'id': 24,
   u'last_name': u'Tsitsuashvili',
   u'sex': 2},
  {u'bdate': u'2.6',
   u'city': {u'id': 2, u'title': u'Saint Petersburg'},
   u'first_name': u'Tatyana',
   u'id': 34,
   u'last_name': u'Plutalova',
   u'sex': 1},
  {u'deactivated': u'banned',
   u

Тем самым получим лист user_lists из 10 листов по 100 пользователей (для примера указаны порядковые номера пользователей от 0 до 999):

In [120]:
user_lists = [ [0, 1, 2, ...], [100, 101, 102, ...], ..., [997, 998, 999] ]

Строчку с ID пользователей для запроса к API ВКонтакте из листа можно получить так:

In [123]:
users_list = [1, 2, 3]
users_list = [str(x) for x in users_list]
users_string = ','.join(users_list)
print(users_string)

1,2,3


### Упражнение

Вам необходимо:

1. Получить список 1000 пользователей Хабра и записать их в лист user_ids. Используйте стандартную сортировку пользователей по возрастанию user_id (как в примерах текущего шага).

2. Разбить этот лист на лист user_lists по 100 пользователей.

2. Для этих пользователей посчитать распределение по городам (аналогично тому, как считали распределение по полу в прошлом блоке) и записать результат в словарь city_dict. Пример словаря city_dict можно посмотреть ниже.

Какой город занимает первое место по числу пользователей в city_dict?

In [113]:
#url = 'https://api.vk.com/method/groups.getMembers'

In [120]:
#token = "a1644697a1644697a1644697b3a10d9eddaa164a1644697fdc8c473592d0747db2d2332"
#token = 'd4b67cd4d4b67cd4d4b67cd4ced4dfadacdd4b6d4b67cd4881d441845cd205888a5e499'
'fields': 'city',

In [207]:
count = 100
offset = 0
user_ids = []
while offset < 1000:
    print('Выгружаю {} пользователей с offset = {}'.format(count, offset))   
    params = {
        'group_id': 'habr',
        'v': 5.73,
        'count': count,
        'offset': offset,
        'access_token': token
    }   
    # такой же запрос как в прошлый раз
    r = requests.get(url, params = params)
    data = r.json()   
    user_ids += data['response']['items'] 
    print (data['response']['items'])

    # увеличиваем смещение на количество строк выгрузки
    offset += count

Выгружаю 100 пользователей с offset = 0
[6, 10, 11, 17, 24, 34, 47, 55, 57, 161, 169, 239, 243, 251, 341, 345, 347, 348, 404, 409, 453, 478, 480, 485, 488, 489, 510, 512, 530, 550, 591, 616, 619, 628, 630, 634, 669, 687, 702, 718, 720, 804, 834, 880, 885, 891, 905, 914, 952, 966, 975, 979, 982, 985, 1004, 1010, 1038, 1091, 1097, 1109, 1127, 1139, 1159, 1174, 1198, 1200, 1211, 1215, 1242, 1278, 1331, 1338, 1346, 1351, 1381, 1473, 1479, 1481, 1496, 1500, 1507, 1523, 1544, 1583, 1587, 1615, 1624, 1632, 1644, 1667, 1668, 1690, 1697, 1699, 1708, 1710, 1721, 1736, 1754, 1772]
Выгружаю 100 пользователей с offset = 100
[1786, 1794, 1814, 1828, 1829, 1834, 1835, 1839, 1843, 1857, 1860, 1867, 1880, 1906, 1946, 1964, 1967, 2008, 2019, 2050, 2051, 2075, 2103, 2131, 2150, 2176, 2206, 2209, 2229, 2230, 2281, 2284, 2298, 2310, 2322, 2341, 2373, 2389, 2395, 2407, 2410, 2461, 2463, 2472, 2484, 2492, 2539, 2541, 2542, 2592, 2609, 2615, 2619, 2622, 2635, 2658, 2693, 2718, 2720, 2722, 2729, 2752, 2756, 27

In [215]:
type(user_ids)

list

In [218]:
len(user_ids)

1000

In [217]:
for user in user_ids:
    print(user)

6
10
11
17
24
34
47
55
57
161
169
239
243
251
341
345
347
348
404
409
453
478
480
485
488
489
510
512
530
550
591
616
619
628
630
634
669
687
702
718
720
804
834
880
885
891
905
914
952
966
975
979
982
985
1004
1010
1038
1091
1097
1109
1127
1139
1159
1174
1198
1200
1211
1215
1242
1278
1331
1338
1346
1351
1381
1473
1479
1481
1496
1500
1507
1523
1544
1583
1587
1615
1624
1632
1644
1667
1668
1690
1697
1699
1708
1710
1721
1736
1754
1772
1786
1794
1814
1828
1829
1834
1835
1839
1843
1857
1860
1867
1880
1906
1946
1964
1967
2008
2019
2050
2051
2075
2103
2131
2150
2176
2206
2209
2229
2230
2281
2284
2298
2310
2322
2341
2373
2389
2395
2407
2410
2461
2463
2472
2484
2492
2539
2541
2542
2592
2609
2615
2619
2622
2635
2658
2693
2718
2720
2722
2729
2752
2756
2758
2821
2827
2832
2871
2911
2914
2932
2933
2946
2981
2983
3006
3020
3050
3073
3100
3110
3151
3153
3161
3226
3250
3254
3259
3300
3304
3328
3377
3402
3407
3412
3420
3422
3427
3443
3450
3486
3491
3516
3523
3548
3597
3644
3646
3647
3653
3674
3688
3697

In [219]:
for user in user_ids:
    params = {
        'user_id': user,
        'v': 5.52,
        'access_token': token
    }   
    r = requests.get(url, params = params)
    print(r.json())

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'6', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'10', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'11', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'17', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'628', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'630', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'634', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'669', u'key': u'user_id'}, {u'value': u'5.52', u'key

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'1242', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'1278', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'1331', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'1338', u'key': u'user_id'}, {u'value': u'5.52', u

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'1794', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'1814', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'1828', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'1829', u'key': u'user_id'}, {u'value': u'5.52', u

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'2373', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'2389', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'2395', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'2407', u'key': u'user_id'}, {u'value': u'5.52', u

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'2932', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'2933', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'2946', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'2981', u'key': u'user_id'}, {u'value': u'5.52', u

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'3548', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'3597', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'3644', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'3646', u'key': u'user_id'}, {u'value': u'5.52', u

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'4310', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'4318', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'4377', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'4439', u'key': u'user_id'}, {u'value': u'5.52', u

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'4921', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'4925', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'4944', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'4967', u'key': u'user_id'}, {u'value': u'5.52', u

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'5716', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'5733', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'5794', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'5797', u'key': u'user_id'}, {u'value': u'5.52', u

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'6251', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'6255', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'6260', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'6293', u'key': u'user_id'}, {u'value': u'5.52', u

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'6995', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'7012', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'7014', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'7037', u'key': u'user_id'}, {u'value': u'5.52', u

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'7799', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'7833', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'7837', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'7840', u'key': u'user_id'}, {u'value': u'5.52', u

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'8418', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'8422', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'8426', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'8485', u'key': u'user_id'}, {u'value': u'5.52', u

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'9022', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'9028', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'9040', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'9088', u'key': u'user_id'}, {u'value': u'5.52', u

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'9574', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'9579', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'9611', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'9631', u'key': u'user_id'}, {u'value': u'5.52', u

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'10480', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'10496', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'10518', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'10549', u'key': u'user_id'}, {u'value': u'5.52

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'11713', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'11786', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'11816', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'11848', u'key': u'user_id'}, {u'value': u'5.52

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'12502', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'12545', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'12602', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'12608', u'key': u'user_id'}, {u'value': u'5.52

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'13085', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'13135', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'13158', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'13161', u'key': u'user_id'}, {u'value': u'5.52

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'13907', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'13933', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'13935', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'13991', u'key': u'user_id'}, {u'value': u'5.52

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'14804', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'14838', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'14842', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'14854', u'key': u'user_id'}, {u'value': u'5.52

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'15485', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'15491', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'15537', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'15544', u'key': u'user_id'}, {u'value': u'5.52

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'16435', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'16450', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'16452', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'16474', u'key': u'user_id'}, {u'value': u'5.52

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'17556', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'17582', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'17583', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'17589', u'key': u'user_id'}, {u'value': u'5.52

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'18305', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'18311', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'18312', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'18358', u'key': u'user_id'}, {u'value': u'5.52

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'18934', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'18939', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'18944', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'18969', u'key': u'user_id'}, {u'value': u'5.52

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'19584', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'19596', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'19611', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'19691', u'key': u'user_id'}, {u'value': u'5.52

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'20471', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'20510', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'20551', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'20591', u'key': u'user_id'}, {u'value': u'5.52

{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'21378', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'21383', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'21401', u'key': u'user_id'}, {u'value': u'5.52', u'key': u'v'}]}}
{u'error': {u'error_code': 125, u'error_msg': u'Invalid group id', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'groups.getMembers', u'key': u'method'}, {u'value': u'21417', u'key': u'user_id'}, {u'value': u'5.52

In [107]:
offset

1000

In [108]:
user_ids

[6,
 10,
 11,
 17,
 24,
 34,
 47,
 55,
 57,
 161,
 169,
 239,
 243,
 251,
 341,
 345,
 347,
 348,
 404,
 409,
 453,
 478,
 480,
 485,
 488,
 489,
 510,
 512,
 530,
 550,
 591,
 616,
 619,
 628,
 630,
 634,
 669,
 687,
 702,
 718,
 720,
 804,
 834,
 880,
 885,
 891,
 905,
 914,
 952,
 966,
 975,
 979,
 982,
 985,
 1004,
 1010,
 1038,
 1091,
 1097,
 1109,
 1127,
 1139,
 1159,
 1174,
 1198,
 1200,
 1211,
 1215,
 1242,
 1278,
 1331,
 1338,
 1346,
 1351,
 1381,
 1473,
 1479,
 1481,
 1496,
 1500,
 1507,
 1523,
 1544,
 1583,
 1587,
 1615,
 1624,
 1632,
 1644,
 1667,
 1668,
 1690,
 1697,
 1699,
 1708,
 1710,
 1721,
 1736,
 1754,
 1772,
 1786,
 1794,
 1814,
 1828,
 1829,
 1834,
 1835,
 1839,
 1843,
 1857,
 1860,
 1867,
 1880,
 1906,
 1946,
 1964,
 1967,
 2008,
 2019,
 2050,
 2051,
 2075,
 2103,
 2131,
 2150,
 2176,
 2206,
 2209,
 2229,
 2230,
 2281,
 2284,
 2298,
 2310,
 2322,
 2341,
 2373,
 2389,
 2395,
 2407,
 2410,
 2461,
 2463,
 2472,
 2484,
 2492,
 2539,
 2541,
 2542,
 2592,
 2609,
 2615,


In [134]:
rows_limit = 100
user_lists = []
position = 0
while position < len(user_ids):
    user_lists.append( user_ids[position:position + rows_limit] )
    position += rows_limit

In [135]:
user_lists

[[6,
  10,
  11,
  17,
  24,
  34,
  47,
  55,
  57,
  161,
  169,
  239,
  243,
  251,
  341,
  345,
  347,
  348,
  404,
  409,
  453,
  478,
  480,
  485,
  488,
  489,
  510,
  512,
  530,
  550,
  591,
  616,
  619,
  628,
  630,
  634,
  669,
  687,
  702,
  718,
  720,
  804,
  834,
  880,
  885,
  891,
  905,
  914,
  952,
  966,
  975,
  979,
  982,
  985,
  1004,
  1010,
  1038,
  1091,
  1097,
  1109,
  1127,
  1139,
  1159,
  1174,
  1198,
  1200,
  1211,
  1215,
  1242,
  1278,
  1331,
  1338,
  1346,
  1351,
  1381,
  1473,
  1479,
  1481,
  1496,
  1500,
  1507,
  1523,
  1544,
  1583,
  1587,
  1615,
  1624,
  1632,
  1644,
  1667,
  1668,
  1690,
  1697,
  1699,
  1708,
  1710,
  1721,
  1736,
  1754,
  1772],
 [1786,
  1794,
  1814,
  1828,
  1829,
  1834,
  1835,
  1839,
  1843,
  1857,
  1860,
  1867,
  1880,
  1906,
  1946,
  1964,
  1967,
  2008,
  2019,
  2050,
  2051,
  2075,
  2103,
  2131,
  2150,
  2176,
  2206,
  2209,
  2229,
  2230,
  2281,
  2284,
  2298,

ВИЗУАЛИЗАЦИЯ ОТЧЕТА ДЛЯ ГРУППЫ N+1

Данные получены, осталось построить отчет рейтинга городов по числу участников. Пример ниже посчитан для группы "N+1" (https://vk.com/nplusone), а не Хабра.

После выполнения упражнения у вас будет сформирован словарь city_dict вида:

In [125]:
# Давайте посмотрим, как визуализировать этот отчет с помощью Pandas:

import pandas as pd
# Переводим словарь city_dict в датафрейм:

df = pd.DataFrame.from_dict(city_dict, orient = 'index').reset_index()

NameError: name 'city_dict' is not defined

In [127]:
# Переименовываем для удобства названия столбцов и сортируем датафрейм:

df.rename(columns = {'index': 'city', 0: 'users'}, inplace = True)
df = df.sort_values('users', ascending = False)
df.head()

users           1
0  рублей за грамм  06.04.2019
2       Серебро Ag        3195
3       Платина Pt    1 909,42
4      Палладий Pd    2 815,77
1        Золото Au    2 710,41

In [128]:
# Возьмем первые три города с количеством пользователей более 100, а остальные значения определим как "другие":

df['category'] = df.apply(lambda x: x['city'] if x['users'] > 100 else 'другие', axis = 1)

#Сгруппируем по столбцу category:

df = df.groupby('category').sum().head()

#Визуализируем результат:

%matplotlib inline
df.head().plot(kind = 'pie', y = 'users', figsize= (7, 7))

TypeError: ("'>' not supported between instances of 'str' and 'int'", 'occurred at index 0')

# Блок 7. Домашнее задание. Топовые посты группы > Шаг 1. Авторизация в API

На этом шаге мы составим отчет по лучшим постам группы за прошедшую неделю.

Под лучшими постами будем понимать те, что набрали наибольшее количество лайков, репостов и комментариев.

Для решения этой задачи попутно изучим пример прохождения авторизации для запросов к API ВКонтакте, т. к. нужный метод wall.get требует сервисного токена. А также познакомимся с форматом файлов YAML, который позволяет удобно работать с параметрами скрипта и паролями.

Авторизация применяется практически во всех API, чтобы отдавать данные только их владельцу или контролировать количество запросов в единицу времени. Сервисный токен для нашей задачи создается вместе с новым приложением. Приложение мы делать, конечно, не будем. Оно нужно только для получения токена, чтобы сделать необходимые выгрузки.

Зайдите на страницу https://vk.com/editapp?act=create, чтобы создать приложение (вы должны быть авторизованы ВКонтакте). Дайте приложению любое название и оставьте значение платформы "Standalone-приложение":

После подтверждения создания приложения в приложении ВК или по СМС зайдите в настройки:

Нужный нам токен лежит в поле "Сервисный ключ доступа".

### Формат YAML

Теперь необходимо передавать этот ключ с каждым запросом с методом wall.get. Возникает проблема: как хранить этот ключ. Просто записать его в переменную в коде не лучшая идея.

Это относится вообще к любым токенам, паролям, ключам и другой чувствительной информации по крайней мере по двум причинам:

При отправке кому-либо файла с кодом или сохранении в другом месте ваш ключ может быть доступен другому человеку. Еще хуже, если вы случайно сохраните его на общем сетевом диске или открытом репозитории на Github.
Ключ, который продолжительное время виден на вашем экране (пока вы пишете код), также не добавляет безопасности вашему приложению.
Для частичного решения этих проблем, а также хранения внешних переменных вне кода, был разработан формат YAML. 

Он позволяет записывать ваши переменные и их значения в файл, а затем импортировать их в код в JSON-формате. Это гораздо удобнее, чем читать обычный файл построчно и доставать из него нужные вам строки. Также в YAML-файлах можно оставлять комментарии к параметрам.

Т. е. его отличие YAML-формата от обычного текстового файла в том, что Python (и другие языки программирования) может распознавать его содержимое как словарь.

Файл config_example.yaml

Рассмотрим пример чтения YAML-файла config_example.yaml. Содержимое файла (файл открыт в редакторе Sublime Text):

In [7]:
#В питоне для чтения YAML-файлов использовать стандарную библиотеку yaml:

from yaml import load
f = open('config_example_my.yaml', mode = 'r', encoding = 'utf-8')
config = load(f)

In [8]:
config

{'access_token': 'a1644697a1644697a1644697b3a10d9eddaa164a1644697fdc8c473592d0747db2d2332',
 'mysql': {'host': '10.0.108.8',
  'port': 3306,
  'database': 'scoring',
  'user': 'defaultuser',
  'password': 'passw@rd'},
 'cities': ['Москва',
  'Санкт-Петербург',
  'Волгоград',
  'Новороссийск',
  'Тула',
  'Мурманск',
  'Смоленск',
  'Севастополь',
  'Одесса',
  'Киев',
  'Керчь',
  'Минск']}

# Разбор задачи с сайта про Бот

https://itnan.ru/post.php?c=1&p=427691

Приступим к программной части бота

Мы не будем реализовывать его через запросы к ВК, а если быть точнее, просто используем библиотеку VkLongPool, которая сделает это за нас.

Для этого необходима библиотека vk_api. Установим его через pip:

python -m pip install vk_api

Successfully installed vk-api-11.4.0

In [2]:
import vk_api  # 2 Питон

In [12]:
from vk_api.longpoll import VkLongPoll, VkEventType  # 2 Питон

In [48]:
from vk_api.bot_longpoll import VkBotLongPoll, VkBotEventType

In [13]:
def write_msg(user_id, message):
    vk.method('messages.send', {'user_id': user_id, 'message': message})

In [99]:
# API-ключ созданный ранее
token = "c02d3ce87bb1c6840fc1b1a7c34a868d3dbd01b254e1f09a7b9aed6ae1312fbf24542b16419bad4baddc7"

In [84]:
access_token = "c02d3ce87bb1c6840fc1b1a7c34a868d3dbd01b254e1f09a7b9aed6ae1312fbf24542b16419bad4baddc7"

In [102]:
# API-ключ созданный ранее
token = "a1644697a1644697a1644697b3a10d9eddaa164a1644697fdc8c473592d0747db2d2332"

In [85]:
# Авторизуемся как сообщество
vk = vk_api.VkApi(token=token)
vk

In [86]:
vk._auth_token()

In [87]:
vk.get_api()

In [89]:
longpoll = VkBotLongPoll(vk, v=access_token)

TypeError: __init__() got an unexpected keyword argument 'v'

In [103]:
requests.get('https://api.vk.com/method/messages.getLongPollServer', params={'access_token': token})

<Response [200]>

In [100]:
requests.get('https://api.vk.com/method/messages.getLongPollServer', params={'access_token': token}).json()

{u'error': {u'error_code': 8,
  u'error_msg': u'Invalid request: v (version) is required',
  u'request_params': [{u'key': u'oauth', u'value': u'1'},
   {u'key': u'method', u'value': u'messages.getLongPollServer'}]}}

In [94]:
import requests
#token = ''  # здесь вы должны написать свой access_token
data = requests.get('https://api.vk.com/method/messages.getLongPollServer', params={'access_token': token}).json()['response']  # получение ответа от сервера
print(data)

KeyError: u'response'

https://habr.com/ru/post/335106/

In [69]:
print(vk.method('users.get', {'user_ids': 25, 'fields': 'city, verified'}))

[{u'city': {u'id': 2, u'title': u'\u0421\u0430\u043d\u043a\u0442-\u041f\u0435\u0442\u0435\u0440\u0431\u0443\u0440\u0433'}, u'first_name': u'\u0410\u043d\u0430\u0441\u0442\u0430\u0441\u0438\u044f', u'last_name': u'\u0412\u0435\u0434\u0443\u0449\u0435\u043d\u043a\u043e', u'verified': 0, u'can_access_closed': False, u'id': 25, u'is_closed': True}]


In [47]:
import requests
data = requests.get('https://api.vk.com/method/{METHOD_NAME}'.format(METHOD_NAME='users.get'),
                    params={'user_ids': 2, 'fields': 'sex, city, verified'}).json()
print(data)

{u'error': {u'error_code': 5, u'error_msg': u'User authorization failed: no access_token passed.', u'request_params': [{u'value': u'1', u'key': u'oauth'}, {u'value': u'users.get', u'key': u'method'}, {u'value': u'sex, city, verified', u'key': u'fields'}, {u'value': u'2', u'key': u'user_ids'}]}}


In [ ]:
r = requests.get('https://www.cbr-xml-daily.ru/daily_json.js')

Что же здесь происходит? Мы вызываем метод method, передавая ему два аргумента: первый — название метода API, второй — словарь из параметров этого метода. Список всех методов и их параметров находится в документации API. В данном случае мы вызываем метод «users.get» и передаем следующие параметры: «user_ids» — список id пользователей, для которых мы хотим получить данные, «fields»: дополнительную информацию о пользователях: аватарку и город проживания. Результатом выполнения программы будет следующая выведенная строка: [{'id': 210700286, 'first_name': 'Lindsey', 'last_name': 'Stirling', 'city': {'id': 5331, 'title': 'Los Angeles'}, 'photo_50': 'https://pp.userapi.com/c636821/v636821286/38a75/Ay-bEZoJZw8.jpg'}]

In [16]:
# Работа с сообщениями
longpoll = VkLongPoll(vk)

ApiError: [15] Access denied: group messages are disabled

In [ ]:


# Основной цикл
for event in longpoll.listen():

    # Если пришло новое сообщение
    if event.type == VkEventType.MESSAGE_NEW:
    
        # Если оно имеет метку для меня( то есть бота)
        if event.to_me:
        
            # Сообщение от пользователя
            request = event.text
            
            # Каменная логика ответа
            if request == "привет":
                write_msg(event.user_id, "Хай")
            elif request == "пока":
                write_msg(event.user_id, "Пока((")
            else:
                write_msg(event.user_id, "Не поняла вашего ответа...")